global using ProgressionJournal.Data.Catalogs;
global using ProgressionJournal.Data.Enums;
global using ProgressionJournal.Data.Models;
global using ProgressionJournal.Data.Repositories;
global using ProgressionJournal.UI.Composition;
global using ProgressionJournal.UI.Controls;
global using ProgressionJournal.UI.States;
global using ProgressionJournal.UI.Styling;
global using ProgressionJournal.UI.Utilities;
